service: sba-users-api

provider:
  name: aws
  profile: sba-dm
  runtime: nodejs6.10
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  iamRoleStatements:
      - Effect: "Allow"
        Resource: "arn:aws:cognito-idp:us-east-1:992097552520:userpool/*"
        Action:
          - "cognito-idp:*"
  environment:
    USER_POOL_ID: ${file(./config/config.${self:provider.stage}.json):userPoolId}

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'



plugins:
  - serverless-offline
